# Generated by Django 4.2.3 on 2023-07-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=200)),
                ('adminPASSWORD', models.CharField(max_length=200)),
                ('adminEMAIL', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventNAME', models.CharField(max_length=200)),
                ('eventDATE', models.DateField()),
                ('eventDISCRIPTION', models.TextField()),
                ('eventLOCATION', models.CharField(max_length=200)),
                ('eventSTARTTIME', models.TimeField()),
                ('eventIMAGE', models.ImageField(null=True, upload_to='uploads/images')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizerID', models.AutoField(primary_key=True, serialize=False)),
                ('organizerNAME', models.CharField(max_length=200)),
                ('organizerEMAIL', models.EmailField(max_length=200)),
                ('organizerREGNO', models.CharField(max_length=200)),
                ('organizerPHONE', models.CharField(max_length=20)),
                ('organizerPASSWORD', models.CharField(max_length=200, null=True)),
                ('organizerCONPASSWORD', models.CharField(max_length=200, null=True)),
                ('organizerNIC', models.CharField(max_length=20)),
                ('organizerIMAGE', models.ImageField(null=True, upload_to='uploads/images')),
                ('addressLINE1', models.CharField(default='', max_length=200)),
                ('addressLINE2', models.CharField(default='', max_length=200)),
                ('organizerCITY', models.CharField(default='', max_length=200)),
                ('organizerAGREED', models.BooleanField(default=False)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.admin')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('qrcodeID', models.AutoField(primary_key=True, serialize=False)),
                ('qrDATA', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDashboard',
            fields=[
                ('dashboardID', models.AutoField(primary_key=True, serialize=False)),
                ('topSellingEvents', models.TextField()),
                ('totalRevenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('organizerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userNAME', models.CharField(max_length=200)),
                ('userEMAIL', models.EmailField(max_length=200)),
                ('USERPASSWORD', models.CharField(max_length=200)),
                ('userPHONE', models.CharField(max_length=20)),
                ('userNIC', models.CharField(max_length=20)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.admin')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticketT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ticketT_NAME', models.CharField(max_length=200)),
                ('ticketT_PRICE', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ticketDISCRIPTION', models.TextField()),
                ('ticketT_QUANTITY', models.IntegerField()),
                ('organizerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('ticketSTATUS', models.CharField(max_length=200)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ticketT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('nic', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=200)),
                ('ticketT_NAME', models.CharField(max_length=200)),
                ('ticketQUANTITY', models.IntegerField()),
                ('ticketSUBTOTAL', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dashboardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.salesdashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('paymentSTATUS', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('nic', models.CharField(max_length=20)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderAMOUNT', models.DecimalField(decimal_places=2, max_digits=7)),
                ('orderTIME', models.DateTimeField(auto_now_add=True)),
                ('orderSTATUS', models.CharField(max_length=200)),
                ('orderDATE', models.DateField()),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.payment')),
                ('qrcodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.qrcode')),
                ('ticketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ticket')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organizerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organizer'),
        ),
    ]
