# Generated by Django 4.2.3 on 2023-07-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USERPASSWORD',
            new_name='userPASSWORD',
        ),
    ]
