# Generated by Django 4.2.3 on 2023-07-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_userpassword_user_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adminID',
        ),
    ]
